version: '2'
services:
  jdemo3-app:
    image: jdemo3
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jdemo3-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jdemo3
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  jdemo3-mongodb:
    extends:
      file: mongodb.yml
      service: jdemo3-mongodb
